### ISSUE TITLE
Size snaps when starting resize using flex containers

### ISSUE THREAD

**Issue by xQsme** [bokuweb/re-resizable#518] opened 2019-09-05 16:46 UTC
This might be my fault as I'm not very familiar with css in general...

https://codesandbox.io/embed/new-platform-k2uhj

when resizing any of the divs they snap and become bigger than they were before unintentionally

I'm using re-resizable 6.0.0 on Firefox

**Comment by Lukavyi** [comment] 2019-09-24 08:52
same for me

**Comment by dancron** [comment] 2019-09-27 21:11
It looks like the problem is specific to flexGrow. If you delete the lines with flexGrow, the snap at the beginning of the resizing goes away.

Not an answer, but a start on narrowing down the issue. Without flexGrow, I have to use a different method of specifying the initial size. The solution would be to get this to work with flexGrow.

**Comment by GRSGreck** [comment] 2020-12-01 15:25
Hi @xQsme!

I have one [solution](https://codesandbox.io/s/re-resizable-iohpt?file=/src/App.js) to this issue.
It's not working completely fine, however, you can use it as a temporary solution till this issue will be fixed.

**Closed** 2022-06-29 15:44 UTC
Labels: help wanted, PR_Welcome
